language: python
python:
  - "3.6"
cache:
  directories:
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: taken0711-github
    token: $SONAR_TOKEN
install:
  - python -m unittest
notifications:
  email: false