language: python
python:
  - "3.6"
cache:
  directories:
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: taken0711-github
    token: $SONAR_TOKEN
install:
  - pip install -r requirements.txt
script:
  - nosetests --with-coverage --cover-xml --with-xunit
  - sonar-scanner
  - bash <(curl -s https://codecov.io/bash)
  - mut -t simulator -u simulator.tests
notifications:
  email: false